server:
  port: 8060
  ssl:
    key-store: classpath:ssl/6276014_www.homeplus.fun.pfx
    key-store-type: PKCS12
    key-store-password: sp1Sip8h

spring:
  application:
    name: api-getway
  cloud:
    nacos:
      discovery:
        server-addr: 172.19.87.61:8090
        namespace: 622aa46c-9f6f-4620-908d-61232ec9c438
        ip: 127.0.0.1

    gateway:
      routes:
        - id: searoad_route
          uri: lb://searoad
          predicates:
            - Path=/searoad_server/**
          filters:
            - StripPrefix=1

        - id: h5_route
          uri: lb://h5
          predicates:
            - Path=/h5_server/**
          filters:
            - StripPrefix=1

        - id: system_route
          uri: lb://system
          predicates:
            - Path=/system_server/**
          filters:
            - StripPrefix=1

        - id: club_route
          uri: lb://club
          predicates:
            - Path=/club_server/**
          filters:
            - StripPrefix=1
#
#        - id: focus_route
#          uri: lb://focus
#          predicates:
#            - Path=/focus_server/**
#          filters:
#            - StripPrefix=1
#
#        - id: mainindex_route
#          uri: lb://mainindex
#          predicates:
#            - Path=/mainindex_server/**
#          filters:
#            - StripPrefix=1
#
#        - id: report_route
#          uri: lb://report
#          predicates:
#            - Path=/report_server/**
#          filters:
#            - StripPrefix=1
#
#        - id: sta_route
#          uri: lb://shops
#          predicates:
#            - Path=/shops_server/**
#          filters:
#            - StripPrefix=1

      # 网关跨域配置start---------------------------------
      # 开启网关的跨域功能，具体微服务上的跨域需要进行关闭，否则无效
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowed-headers: "*"
            allowedOrigins: "*" # 跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
        # 网关跨域配置end---------------------------------


const:
  nointercetorpath: .*/((sys/getVerificationCode/*)|(sys/login/*)).*
