
#服务配置
server:
  port: 8004

#spring配置
spring:
  #1.应用配置
  application:
    name: h5 #指定服务名
  cloud:
    nacos:
      discovery:
        server-addr: 172.19.87.61:8090
        namespace: 622aa46c-9f6f-4620-908d-61232ec9c438
        ip: 127.0.0.1

  redis:
    host: 47.100.171.118
    port: 6400
    password: 1qaz@WSX


  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.171.118:3306/searoad?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz@WSX

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xulei.cn.entities.wechath5
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl







